# 当前工厂的二维化地图，指出工厂中存在的不可通过的点

config:
  width: 20
  height: 30

  blocks:
    - zone:
        id: 1
        zone: [1, 2, 10, 12]

  points:
    - point:
        id: 1
        coordinate: [8, 9]
    - point:
        id: 2
        coordinate: [12, 23]
    - point:
        id: 3
        coordinate: [ 22, 10 ]
  machines:
    - machine:
        id: 1
        type: packet_factory.Machine
        location: point@1
    - machine:
        id: 2
        type: packet_factory.Machine
        location: point@2

  paths:
    - path:
        id: 1
        type: bi
        begin: 1
        end: 2
    - path:
        id: 2
        type: uni
        begin: 2
        end: 3

  agvs:
    - agv:
        type: packet_factory.Agv
        location: point@1
        velocity: 10
        capacity: 12
    - agv:
        type: packet_factory.Agv
        location: point@2
        velocity: 1
        capacity: 12
