config:
  env_type: simulation
  simulation:
    agent:
      agent_name: packet_factory.RandomAgent
      id: 1
      name: 1
    callback:
      agent_callback:
        after_decision:
          args: []
          name: base_callback.AfterDecision
        before_decision:
          args: []
          name: base_callback.BeforeDecision
      agv_callback:
        after_work:
          args: []
          name:
          - agv_callback.BaseCount
      job_callback:
        after_work:
          args: []
          name:
          - job_callback.BaseCount
      machine_callback:
        after_work:
          args: []
          name:
          - machine_callback.BaseCount
      map_callback:
        event_queue:
          args: []
          name: base_callback.EventQueue
        graph_loader:
          args: []
          name: backend_callback.MapLoader
        visualizer:
          args:
          - 3
          name: backend_callback.Visualizer
    env_name: packet_factory
    event_config:
      file: E:\Project\PythonPro\tiangong\backend\config_set\pipeline_config_set\event_config.yaml
    factory_config:
      file: E:\Project\PythonPro\tiangong\backend\config_set\pipeline_config_set\map_config.yaml
    task_config:
      file: E:\Project\PythonPro\tiangong\backend\config_set\pipeline_config_set\job_config.yaml
